### ISSUE TITLE
关于随机回复功能无法查看添加的列表

### ISSUE THREAD

**Issue by BrKnifv** [HeadmasterTan/zhi-plugin#1]
大佬，我把表情添加到插件里，云崽的#表情列表提取不了有多少表情了怎么办啊😂
![image](https://user-images.githubusercontent.com/75532640/176828438-c8762149-249f-43d1-81d4-2c9c2f34297c.png)
![image](https://user-images.githubusercontent.com/75532640/176828514-d7a85b77-de2e-429e-bd89-ff53348ab1f8.png)

**Comment by HeadmasterTan** [comment]
因为这功能没做啦😂`表情列表`依然是原来云崽的功能

原本是想做的，但是表情种类分了太多了
文字、图片、文字+图片、视频，还有转发或者其他（没有文件）

而且随机回复是一指令对多表情，再加上表情的多样化，我脑袋直接死机不知该怎么做了😰（不是摆烂哦😆）
