### ISSUE TITLE
添加表情不能识别图片

### ISSUE THREAD

**Issue by llloli** [HeadmasterTan/zhi-plugin#15]
能识别文本和文字+图片，但是单张图片就无法识别。

**Comment by HeadmasterTan** [comment]
确实有问题，不过是在V3出的问题，V2和喵喵V2是可以的
我排查下吧，尽快修复🧐

**Comment by cj0928** [comment]
> 确实有问题，不过是在V3出的问题，V2和喵喵V2是可以的
> 
> 我排查下吧，尽快修复🧐

还有一个聊天记录好像也不行

**Comment by mmmooyuFei** [comment]
> 

关于这个问题,我刚才看了一下, 在./adapter/index.js的
第24,25行代码中    let msg = e.original_msg || '';    if (!msg) {return false}
如果是表情图片之类的消息,这个e.original_msg的值是undefined,所以不能将这个作为唯一判断条件.
表情消息的raw_message值是'[动画表情]',图片消息的raw_message值是'[图片]'

**Comment by vgwik** [comment]
> 确实有问题，不过是在V3出的问题，V2和喵喵V2是可以的 我排查下吧，尽快修复🧐

这个添加表情功能未修复的情况下能否在config文件中禁用（使用Yunzai默认的添加方法），并保留B站动态推送功能？
刚刚看到Issues中有一个动态转发图片的，感觉如果可以做出来应该不错。
想请问一下，在文字状态下可否新增表达的效果？（简要转发和全文转发）
我试了一下动态，它只能转发一部分的文字（B站有6行，只转发了2行）、图片，能否将B站的动态中的全文转发？
新功能建议，如果可以，也许可以尝试添加推特转发功能（？）
抱歉，可能写的有点长了，GitHub我没有那么熟悉。

**Comment by HeadmasterTan** [comment]
这个问题修复啦~

嗐，真的没空啦，社畜熬不动了，慢速修复和慢速更新中😇

**Comment by HeadmasterTan** [comment]
> > 确实有问题，不过是在V3出的问题，V2和喵喵V2是可以的 我排查下吧，尽快修复🧐
> 
> 这个添加表情功能未修复的情况下能否在config文件中禁用（使用Yunzai默认的添加方法），并保留B站动态推送功能？ 刚刚看到Issues中有一个动态转发图片的，感觉如果可以做出来应该不错。 想请问一下，在文字状态下可否新增表达的效果？（简要转发和全文转发） 我试了一下动态，它只能转发一部分的文字（B站有6行，只转发了2行）、图片，能否将B站的动态中的全文转发？ 新功能建议，如果可以，也许可以尝试添加推特转发功能（？） 抱歉，可能写的有点长了，GitHub我没有那么熟悉。

我做个记录吧，本来是不希望机器人刷屏所以加的限制的，后续有空就把配置加上🧐
