### ISSUE TITLE
佬，B站订阅那个好像有一点小问题

### ISSUE THREAD

**Issue by cj0928** [HeadmasterTan/zhi-plugin#16]
有的人uid太短了好像识别不出来？![image](https://user-images.githubusercontent.com/104024133/190641821-4c2b3807-76af-421b-aeaa-391839e4f507.png)![image](https://user-images.githubusercontent.com/104024133/190641848-fab8a155-5ef3-4682-a06b-d1310ee9e786.jpeg)

**Comment by cj0928** [comment]
大问题，所有订阅都不行，全炸了，佬！你在哪儿？！～～～～～～～

**Comment by HeadmasterTan** [comment]
emmm，猜测可能是地址换了吧，我瞅瞅，稍等下

**Comment by HeadmasterTan** [comment]
可以啦
![QQ截图20220917222711](https://user-images.githubusercontent.com/24260221/190862335-4093d7a1-7914-456b-abbe-59369ab5b54b.png)

更新试试吧

**Comment by cj0928** [comment]
谢谢佬(///▽///)
