### ISSUE TITLE
关于对动态内容不做任何限制该如何修改

### ISSUE THREAD

**Issue by NoelleDLL** [HeadmasterTan/zhi-plugin#3]
大佬 我不太懂JS...额就是在不出BUG的情况下,这两函数核心内容应该怎么改，才不会对动态信息进行限制吖(包括图片，文字啥的)
还是说不能改...
![1](https://user-images.githubusercontent.com/107041728/181518438-d71fc43c-5b52-46a0-830c-19db8a6be406.png)

这里一改功能就失效了...
![2](https://user-images.githubusercontent.com/107041728/181518697-ada47ea1-2268-444d-b77a-543f239e0981.png)

辛苦了大佬

**Comment by HeadmasterTan** [comment]
不做限制的话，不调用`dynamicContentLimit`就好啦。

你看到这个函数一开始是用`\n`切割了字符串，到了后面又以`\n`组合回去了，所以你不调用这个函数，就是以原本的内容展示了🧐

**Comment by NoelleDLL** [comment]
大佬这样对吗？
![Answer](https://user-images.githubusercontent.com/107041728/181722384-1b789612-d216-4447-b5f0-495930dde0bb.png)

**Comment by HeadmasterTan** [comment]
> 大佬这样对吗？ ![Answer](https://user-images.githubusercontent.com/107041728/181722384-1b789612-d216-4447-b5f0-495930dde0bb.png)

你把第一个参数放回去呀😂那个`desc.text`，不然就是空的了

**Comment by NoelleDLL** [comment]
懂了，谢谢大佬！

**Comment by NoelleDLL** [comment]
懂了，谢谢大佬！
