### ISSUE TITLE
请问该插件适配v3版本吗

### ISSUE THREAD

**Issue by ChthollyWn** [HeadmasterTan/zhi-plugin#4]

**Comment by NoelleDLL** [comment]
麻烦看看README吧，不要再问这些无意义的问题了

**Comment by HeadmasterTan** [comment]
不适配，首页有写🙄
最近忙没空更新了，你可以自己适配，我看了下好像并不难

**Comment by HeadmasterTan** [comment]
现在适配啦~😘
不过感觉可能会不稳定，已升级V3的可以试试，没有升级V3的还是先用着旧版吧

我会尽快保证稳定的（咕~
