### ISSUE TITLE
没反应

### ISSUE THREAD

**Issue by Nu1L-404** [HeadmasterTan/zhi-plugin#5]
![Snipaste_2022-08-02_20-54-26](https://user-images.githubusercontent.com/95953449/182379756-6226d5d9-e919-4f24-aa48-ce734086683e.png)
![Snipaste_2022-08-02_20-55-46](https://user-images.githubusercontent.com/95953449/182379890-1ad25517-b22b-4ab2-9e89-1bb43a9cddbe.png)
没反应啊
云崽是2.1.9版本的

**Comment by HeadmasterTan** [comment]
不可能啊，可是云崽 V2版本最新的不是才2.1.8版本么

![QQ图片20220806114338](https://user-images.githubusercontent.com/24260221/183232308-fde9932b-6d57-453c-9158-5c6b048a5321.png)

**Comment by cj0928** [comment]
有喵喵分支云崽，已经2.2.1了

**Comment by HeadmasterTan** [comment]
> 有喵喵分支云崽，已经2.2.1了

啊这。。这个。。。最近没空改，果咩😥

**Comment by HeadmasterTan** [comment]
今天测试了，喵喵的Yunzai-Bot也是兼容的，如果有什么其他问题的话，可以在这里反馈
