### ISSUE TITLE
添加表情相关问题

### ISSUE THREAD

**Issue by saltsea02** [HeadmasterTan/zhi-plugin#6]
请问那个关键词存的表情文字之类的，是存储到哪里的啊？没找到（苦露西），不能看已经设了哪些关键词。还有就是怎么把存表情的功能在每个群分开设置🤔

**Comment by HeadmasterTan** [comment]
`/data/randomApply`

这个路径是云崽的路径。
我没做群区分啦，但是你可以通过更改代码来实现，实现的方式很多。
1、像云崽一样，通过文件夹区分
2、给表情追加来源属性
这样都行

**Comment by saltsea02** [comment]
好的，谢谢
